-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 20:22:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cnfbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cnfbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cnfbd` DEFAULT CHARACTER SET utf8 ;
USE `cnfbd` ;

-- -----------------------------------------------------
-- Table `cnfbd`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnfbd`.`aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(45) NOT NULL,
  `CPFAluno` VARCHAR(15) NOT NULL,
  `dataNascimentoAluno` DATE NOT NULL,
  `statusAluno` INT NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnfbd`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnfbd`.`professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  `dataNascimentoProfessor` DATE NOT NULL,
  `usuarioProfessor` VARCHAR(45) NOT NULL,
  `senhaProfessor` VARCHAR(300) NOT NULL,
  `statusProfessor` INT NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnfbd`.`faculdade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnfbd`.`faculdade` (
  `idFaculdade` INT NOT NULL AUTO_INCREMENT,
  `nomeFaculdade` VARCHAR(45) NOT NULL,
  `descricaoFaculdade` VARCHAR(45) NOT NULL,
  `UFfaculdade` VARCHAR(45) NOT NULL,
  `cidadeFaculdade` VARCHAR(45) NOT NULL,
  `statusFaculdade` INT NOT NULL,
  PRIMARY KEY (`idFaculdade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnfbd`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnfbd`.`disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `nomeDisciplina` VARCHAR(45) NOT NULL,
  `descricaoDisciplina` VARCHAR(45) NOT NULL,
  `statusDisciplina` INT NOT NULL,
  `faculdade_idFaculdade` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`, `faculdade_idFaculdade`),
  CONSTRAINT `fk_disciplina_faculdade1`
    FOREIGN KEY (`faculdade_idFaculdade`)
    REFERENCES `cnfbd`.`faculdade` (`idFaculdade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnfbd`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnfbd`.`turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `nomeTurma` VARCHAR(45) NOT NULL,
  `descricaoTurma` VARCHAR(45) NOT NULL,
  `statusTurma` VARCHAR(45) NOT NULL,
  `disciplina_idDisciplina` INT NOT NULL,
  `professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idTurma`, `disciplina_idDisciplina`, `professor_idProfessor`),
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `cnfbd`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`professor_idProfessor`)
    REFERENCES `cnfbd`.`professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnfbd`.`aluno_has_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnfbd`.`aluno_has_turma` (
  `aluno_idAluno` INT NOT NULL,
  `turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`aluno_idAluno`, `turma_idTurma`),
  CONSTRAINT `fk_aluno_has_turma_aluno1`
    FOREIGN KEY (`aluno_idAluno`)
    REFERENCES `cnfbd`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma_turma1`
    FOREIGN KEY (`turma_idTurma`)
    REFERENCES `cnfbd`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
